CREATE SCHEMA IF NOT EXISTS MA_STUDENT;

DROP TABLE IF EXISTS MA_STUDENT.OFFICES;

 CREATE TABLE MA_STUDENT.OFFICES
   (	OFFICE DECIMAL(38,0),
	CITY VARCHAR(40),
	REGION VARCHAR(30),
	MGR DECIMAL (38,0),
	TARGET DECIMAL (10,0),
	SALES DECIMAL (10,0)
   )
